[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
consensys_zk_goerli = "${CONSENSYS_ZK_GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
